### ISSUE TITLE
Installation problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by viklele** [partkeepr/PartKeepr#665]
I am trying to install partkeepr 0.1.9 on Ubuntu 16.05.

During installation I get the following error:

```
Setting up the database schema...OK
Setting up the admin user...OK
Setting up the part units...OK
Setting up the default footprints...Error

An unexpected error occured during installation. The error message was:
[Syntax Error] line 0, col 69: Error: Expected Literal, got 'ORDER' and happened in /usr/share/php/Doctrine/ORM/Query/QueryException.php:44
```
Please advise. Ubuntu 16.04 has php7.0 installation.

Thanks,
Vikram

**Comment by felicitus** [comment]
Please provide all details as per [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md), especially the database server and version.

**Comment by viklele** [comment]
Here are the other details:

Database: mysql, ver 5.7.  
Browser : FireFox v 46.0.1. 
OS: Ubuntu 16.04 LTS 

Thanks,
Vikram

**Comment by felicitus** [comment]
I just noticed that you are trying to install PartKeepr 0.1.9, which is very old. Have you tried with a more recent version?

**Comment by viklele** [comment]
Dear Timo,

I will try a newer version and get back to you.

Regards,
Vikram

**Comment by pslavkin** [comment]
Hi Felicia, I've exactly the same error on debian 9 with mysql v15.1 but I'd like to preserve my 0.1.9 partkeepr version 'cose I'm used to use that frontend.
If I enter /partkeepr/frontend the systems work, but it didn't show the categories, and if I click on something, the error [Syntax Error] line 0, col 59: Error: Expected Literal, got 'ORDER' appear. 
What do you suggest? Maybe is a matter of a punctuation..
Thanks in advance.

these is the full report
--------------------------------------------------------------------------------------------------------


[Syntax Error] line 0, col 59: Error: Expected Literal, got 'ORDER'

Exception
==================================
Doctrine\ORM\Query\QueryException

Backtrace
==================================
Doctrine\ORM\Query\QueryException

Request
==================================
{"url":"rest.php/PartCategory/getAllCategories","success":null,"failure":null,"method":"POST","params":"{}","headers":{"call":"getAllCategories","lang":"en_US","session":"2sep6gjgf8lrh4et8k8icngu63"}}

Response
==================================
{"status":"systemerror","success":false,"exception":{"message":"[Syntax Error] line 0, col 59: Error: Expected Literal, got 'ORDER'","exception":"Doctrine\\ORM\\Query\\QueryException","backtrace":"#0 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(396): Doctrine\\ORM\\Query\\QueryException::syntaxError('line 0, col 59:...', Object(Doctrine\\ORM\\Query\\QueryException))\n#1 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2363): Doctrine\\ORM\\Query\\Parser->syntaxError('Literal')\n#2 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2550): Doctrine\\ORM\\Query\\Parser->Literal()\n#3 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2485): Doctrine\\ORM\\Query\\Parser->ArithmeticPrimary()\n#4 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2453): Doctrine\\ORM\\Query\\Parser->ArithmeticFactor()\n#5 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2427): Doctrine\\ORM\\Query\\Parser->ArithmeticTerm()\n#6 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2414): Doctrine\\ORM\\Query\\Parser->SimpleArithmeticExpression()\n#7 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2749): Doctrine\\ORM\\Query\\Parser->ArithmeticExpression()\n#8 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2277): Doctrine\\ORM\\Query\\Parser->ComparisonExpression()\n#9 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2177): Doctrine\\ORM\\Query\\Parser->SimpleConditionalExpression()\n#10 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2153): Doctrine\\ORM\\Query\\Parser->ConditionalPrimary()\n#11 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2121): Doctrine\\ORM\\Query\\Parser->ConditionalFactor()\n#12 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(2096): Doctrine\\ORM\\Query\\Parser->ConditionalTerm()\n#13 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(1209): Doctrine\\ORM\\Query\\Parser->ConditionalExpression()\n#14 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(759): Doctrine\\ORM\\Query\\Parser->WhereClause()\n#15 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(726): Doctrine\\ORM\\Query\\Parser->SelectStatement()\n#16 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(229): Doctrine\\ORM\\Query\\Parser->QueryLanguage()\n#17 \/usr\/share\/php\/Doctrine\/ORM\/Query\/Parser.php(304): Doctrine\\ORM\\Query\\Parser->getAST()\n#18 \/usr\/share\/php\/Doctrine\/ORM\/Query.php(233): Doctrine\\ORM\\Query\\Parser->parse()\n#19 \/usr\/share\/php\/Doctrine\/ORM\/Query.php(245): Doctrine\\ORM\\Query->_parse()\n#20 \/usr\/share\/php\/Doctrine\/ORM\/AbstractQuery.php(737): Doctrine\\ORM\\Query->_doExecute()\n#21 \/mnt\/data\/partkeepr\/3rdparty\/doctrine2-nestedset\/lib\/DoctrineExtensions\/NestedSet\/Manager.php(108): Doctrine\\ORM\\AbstractQuery->execute()\n#22 \/mnt\/data\/partkeepr\/3rdparty\/doctrine2-nestedset\/lib\/DoctrineExtensions\/NestedSet\/Manager.php(61): DoctrineExtensions\\NestedSet\\Manager->fetchTreeAsArray(1, NULL)\n#23 \/mnt\/data\/partkeepr\/src\/backend\/PartKeepr\/Category\/AbstractCategoryManager.php(64): DoctrineExtensions\\NestedSet\\Manager->fetchTree(1)\n#24 \/mnt\/data\/partkeepr\/src\/backend\/PartKeepr\/Category\/AbstractCategoryService.php(109): PartKeepr\\Category\\AbstractCategoryManager->getAllCategories()\n#25 \/mnt\/data\/partkeepr\/src\/backend\/PartKeepr\/Service\/ServiceManager.php(131): PartKeepr\\Category\\AbstractCategoryService->getAllCategories()\n#26 \/mnt\/data\/partkeepr\/frontend\/rest.php(56): PartKeepr\\Service\\ServiceManager->call()\n#27 {main}"},"timing":0.052319049835205}

Server Configuration
==================================
doctrine_orm_version: 2.3.3
doctrine_dbal_version: 2.3.4
doctrine_common_version: 2.3.0
php_version: 7.0.30-0+deb9u1
maxUploadSize: 2097152
availableImageFormats: 3FR,AAI,AI,ART,ARW,AVI,AVS,BGR,BGRA,BGRO,BIE,BMP,BMP2,BMP3,BRF,CAL,CALS,CANVAS,CAPTION,CIN,CIP,CLIP,CMYK,CMYKA,CR2,CRW,CUR,CUT,DATA,DCM,DCR,DCX,DDS,DFONT,DJVU,DNG,DOT,DPX,DXT1,DXT5,EPDF,EPI,EPS,EPS2,EPS3,EPSF,EPSI,EPT,EPT2,EPT3,ERF,EXR,FAX,FILE,FITS,FRACTAL,FTP,FTS,G3,G4,GIF,GIF87,GRADIENT,GRAY,GROUP4,GV,H,HALD,HDR,HISTOGRAM,HRZ,HTM,HTML,HTTP,HTTPS,ICB,ICO,ICON,IIQ,INFO,INLINE,IPL,ISOBRL,ISOBRL6,J2C,J2K,JBG,JBIG,JNG,JNX,JP2,JPC,JPE,JPEG,JPG,JPM,JPS,JPT,JSON,K25,KDC,LABEL,M2V,M4V,MAC,MAGICK,MAP,MASK,MAT,MATTE,MEF,MIFF,MKV,MNG,MONO,MOV,MP4,MPC,MPEG,MPG,MRW,MSL,MSVG,MTV,MVG,NEF,NRW,NULL,ORF,OTB,OTF,PAL,PALM,PAM,PANGO,PATTERN,PBM,PCD,PCDS,PCL,PCT,PCX,PDB,PDF,PDFA,PEF,PES,PFA,PFB,PFM,PGM,PICON,PICT,PIX,PJPEG,PLASMA,PNG,PNG00,PNG24,PNG32,PNG48,PNG64,PNG8,PNM,PPM,PREVIEW,PS,PS2,PS3,PSB,PSD,PTIF,PWP,RADIAL-GRADIENT,RAF,RAS,RAW,RGB,RGBA,RGBO,RGF,RLA,RLE,RMF,RW2,SCR,SCT,SFW,SGI,SHTML,SIX,SIXEL,SPARSE-COLOR,SR2,SRF,STEGANO,SUN,SVG,SVGZ,TEXT,TGA,THUMBNAIL,TIFF,TIFF64,TILE,TIM,TTC,TTF,TXT,UBRL,UBRL6,UIL,UYVY,VDA,VICAR,VID,VIFF,VIPS,VST,WBMP,WMF,WMV,WMZ,WPG,X,X3F,XBM,XC,XCF,XPM,XPS,XV,XWD,YCbCr,YCbCrA,YUV
